import { test, expect } from '@playwright/test'

const baseURL = 'http://127.0.0.1:4173'

test('desktop conversion path has no console errors', async ({ page }) => {
  const errors: string[] = []
  page.on('console', (message) => message.type() === 'error' && errors.push(message.text()))
  page.on('pageerror', (error) => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto(baseURL)
  await expect(page.getByRole('heading', { level: 1, name: 'Better Websites. More Calls. More Booked Jobs.' })).toBeVisible()
  await expect(page).toHaveTitle('Local Business Websites & Automation | Phil Greene')
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', 'https://philgreene.net/')
  await expect(page.locator('meta[property="og:image"]')).toHaveAttribute('content', 'https://philgreene.net/og-image.png')
  const schema = await page.locator('script[data-dynamic-schema]').textContent()
  expect(schema).toContain('Google review request systems')
  await page.getByRole('link', { name: 'See Where Leads Get Lost' }).click()
  await expect(page.getByRole('heading', { name: /Every avoidable dead end/ })).toBeInViewport()
  for (const id of ['websites', 'how-it-works', 'automation', 'packages', 'work', 'about', 'audit']) await expect(page.locator(`#${id}`)).toBeAttached()
  expect(errors).toEqual([])
})

test('mobile menu opens and closes with Escape', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(baseURL)
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await expect(page.getByRole('navigation', { name: 'Mobile navigation' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('navigation', { name: 'Mobile navigation' })).toBeHidden()
})

test('audit form sends the intended fields and shows success', async ({ page }) => {
  let body: Record<string, string> | undefined
  await page.route('**/api/contact', async (route) => {
    body = route.request().postDataJSON() as Record<string, string>
    await route.fulfill({ status: 200, contentType: 'application/json', body: '{"ok":true}' })
  })
  await page.goto(`${baseURL}/#audit`)
  await page.getByLabel('Name *', { exact: true }).fill('Sam Owner')
  await page.getByLabel('Business name *', { exact: true }).fill('Sam Service Co')
  await page.getByLabel('Email *', { exact: true }).fill('sam@example.com')
  await page.getByLabel('Phone *', { exact: true }).fill('603-555-0123')
  await page.getByLabel('Website URL', { exact: true }).fill('https://example.com')
  await page.locator('select[name="businessType"]').selectOption('Plumbing')
  await page.getByLabel('Biggest website, lead-capture, or follow-up problem *', { exact: true }).fill('Calls get missed while the team is on a job site.')
  await page.locator('select[name="preferredContact"]').selectOption('Email')
  await page.getByRole('button', { name: 'Get My Free Website Audit' }).click()
  await expect(page.getByRole('heading', { name: 'Your audit request is in.' })).toBeVisible()
  expect(body?.businessName).toBe('Sam Service Co')
  expect(body?.preferredContact).toBe('Email')
})

test('work and demonstrations route renders', async ({ page }) => {
  await page.goto(`${baseURL}/projects`)
  await expect(page.getByRole('heading', { level: 1, name: 'Practical examples of websites, automation, and customer journeys.' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Analytics and reporting' })).toBeVisible()
})

test('Website Checkup recommends a package and prefills empty audit fields', async ({ page }) => {
  await page.goto(baseURL)
  await page.getByRole('button', { name: /Website Checkup/ }).click()
  await page.getByLabel('What kind of business do you run?').selectOption('Roofing')
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('What is your website address?').fill('https://roofer.example')
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('Get more phone calls').check()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('Calls or messages go unanswered').check()
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Complete Lead Recovery System' })).toBeVisible()
  await page.getByRole('button', { name: 'Get My Free Website Audit' }).last().click()
  await expect(page.getByLabel('Website URL', { exact: true })).toHaveValue('https://roofer.example')
  await expect(page.locator('select[name="businessType"]')).toHaveValue('Roofing')
  await expect(page.locator('textarea[name="problem"]')).toHaveValue(/Complete Lead Recovery System/)
})

test('Website Checkup never overwrites audit values already entered', async ({ page }) => {
  await page.goto(`${baseURL}/#audit`)
  await page.getByLabel('Website URL', { exact: true }).fill('https://keep-this.example')
  await page.locator('select[name="businessType"]').selectOption('Plumbing')
  await page.locator('textarea[name="problem"]').fill('Keep this explanation because the visitor wrote it first.')
  await page.getByRole('button', { name: /Website Checkup/ }).click()
  await page.getByLabel('What kind of business do you run?').selectOption('Roofing')
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('Get more phone calls').check()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('The website is unclear or outdated').check()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: 'Get My Free Website Audit' }).last().click()
  await expect(page.getByLabel('Website URL', { exact: true })).toHaveValue('https://keep-this.example')
  await expect(page.locator('select[name="businessType"]')).toHaveValue('Plumbing')
  await expect(page.locator('textarea[name="problem"]')).toHaveValue('Keep this explanation because the visitor wrote it first.')
})

test('Website Checkup supports reset and Escape, and audit errors offer direct email', async ({ page }) => {
  await page.route('**/api/contact', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"Email delivery is temporarily unavailable."}' }))
  await page.goto(baseURL)
  await page.getByRole('button', { name: /Website Checkup/ }).click()
  await page.getByLabel('What kind of business do you run?').selectOption('HVAC')
  await page.getByRole('button', { name: 'Start over' }).click()
  await expect(page.getByLabel('What kind of business do you run?')).toHaveValue('')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.getByRole('button', { name: /Website Checkup/ })).toBeFocused()

  await page.locator('#audit').scrollIntoViewIfNeeded()
  await page.getByLabel('Name *', { exact: true }).fill('Sam Owner')
  await page.getByLabel('Business name *', { exact: true }).fill('Sam Service Co')
  await page.getByLabel('Email *', { exact: true }).fill('sam@example.com')
  await page.getByLabel('Phone *', { exact: true }).fill('603-555-0123')
  await page.locator('select[name="businessType"]').selectOption('HVAC')
  await page.locator('textarea[name="problem"]').fill('The mobile website is difficult to use and leads disappear.')
  await page.locator('select[name="preferredContact"]').selectOption('Email')
  await page.getByRole('button', { name: 'Get My Free Website Audit' }).click()
  await expect(page.getByRole('alert')).toContainText('Email delivery is temporarily unavailable.')
  await expect(page.getByRole('link', { name: 'Email me directly.' })).toHaveAttribute('href', 'mailto:me@philgreene.net')
})
